services:
  gerenciamento_escolar:
    image: gabrielfavar0/escola:v6.2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - escola-rede
    environment:
      - JWT_SECRET_KEY=chaveultrasecretaquenemeunemninguemsabe
      - PASSWORD_SALT=saldosalpessuicosproduzidoporelfosecolhidoporumiete
      - ASPNETCORE_ENVIRONMENT=Development
        
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: escolaDb
    ports:
      - "5433:5432"
    volumes:
      - ~/.postgres_data:/var/lib/postgresql
    networks:
      - escola-rede
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usuario -d escolaDb" ]
      interval: 3s
      timeout: 3s
      retries: 5
      
networks:
  escola-rede:
    driver: bridge